---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 6h
  wait: true
  timeout: 30s
  prune: true
  dependsOn:
    - name: platform
  sourceRef:
    kind: GitRepository
    name: weave-gitops-assured-demo
  path: "./kustomize/apps"