---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 6h
  wait: true
  timeout: 5m
  prune: true
  sourceRef:
    # kind: OCIRepository
    # name: weave-gitops-assured-demo
    kind: Bucket
    name: run-dev-bucket
  path: "./kustomize/platform"