---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-system

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.jetstack.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  install:
    crds: CreateReplace
    remediation:
      retries: 100
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 100
  chart:
    spec:
      chart: cert-manager
      version: 1.8.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager-system
  values:
    installCRDs: true
    securityContext:
      fsGroup: 1001