---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 5m
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:

  releaseName: istio-base
  install:
    crds: Create
    remediation: 
      retries: 100
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      version: "x.x.x"
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  install:
    crds: Create
    remediation: 
      retries: 100
  releaseName: istiod
  dependsOn:
    - name: istio-base
  chart:
    spec:
      version: "x.x.x"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 5m
  values:
    global:
      istioNamespace: istio-system
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
    pilot:
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  timeout: 10m
  releaseName: istio-gateway
  install:
    crds: Create
    remediation: 
      retries: 100
  dependsOn:
    - name: istio-base
    - name: istiod
  chart:
    spec:
      version: "x.x.x"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 5m
  values:
    autoscaling:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    service:
      type: "LoadBalancer"
