apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m
  url: https://weaveworks.github.io/tf-controller

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m
  values:
    envVars:
    - name: WEAVE_GITOPS_FEATURE_TENANCY
      value: "true"
    - name: WEAVE_GITOPS_FEATURE_CLUSTER
      value: "false"
    serviceAccount:
      # -- If `true`, create a new service account
      create: true
