---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 6h
  wait: true
  timeout: 5m
  prune: true
  dependsOn:
    - name: platform
  sourceRef:
    kind: Bucket
    name: run-dev-bucket
  path: "./kustomize/apps"