apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo-podinfo
  namespace: podinfo
spec:
  analysis:
    interval: 10s
    maxWeight: 50
    metrics:
    - interval: 30s
      name: error-rate
      templateRef:
        name: error-rate
        namespace: istio-system
      thresholdRange:
        max: 1
    - interval: 30s
      name: latency
      templateRef:
        name: latency
        namespace: istio-system
      thresholdRange:
        max: 500
    stepWeight: 5
    threshold: 10
    webhooks:
    - metadata:
        cmd: curl -sd 'test' http://podinfo-podinfo-canary.podinfo/token | grep token
        type: bash
      name: acceptance-test
      timeout: 30s
      type: pre-rollout
      url: http://flagger-loadtester.istio-system:80
    - metadata:
        cmd: 'hey -z 1m -q 10 -c 2 -H ''Cookie: type=insider'' http://istio-gateway.istio-system:80'
      name: load-test
      timeout: 5s
      url: http://flagger-loadtester.istio-system:80
  progressDeadlineSeconds: 60
  provider: istio
  service:
    gateways:
    - istio-system/public-gateway
    hosts:
    - '*'
    port: 80
    targetPort: 9898
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo-podinfo