---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 10m0s
  url: https://weavegitops.github.io/application-promotion-podinfo2/
