replicaCount: 2
service:
  enabled: false
  externalPort: 80
canary:
  enabled: true
  loadtester:
    url: "flagger-loadtester.istio-system:80"
  ingress:
    url: "istio-gateway.istio-system:80"
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi